[package]
name = "ecli"
version = "0.1.0"
edition = "2021"
authors = ["etcetera3636@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
